server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE

  config:
    import: configserver:http://localhost:8085
#  cloud:
 #   config:
  #    enabled: false
   #   uri: http://localhost:8085


  #config:
    #import=optional:configserver: http://localhost:8085




